AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'

require:
  - rubocop-rspec
  - rubocop-rake

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'

RSpec/MultipleExpectations:
  Enabled: false
