name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      js_files: ${{ steps.filter.outputs.js_files }}
      ruby_files: ${{ steps.filter.outputs.ruby_files }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            js_files:
              - 'sdks/typescript/**'
              - 'examples/**'
              - 'docs/**'
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'pnpm-workspace.yaml'
              - 'workflows/**'
              - 'tsconfig.base.json'
              - 'vitest.config.ts'
              - 'vitest.setup.ts'
            ruby_files:
              - 'sdks/ruby/**'

  js_build_and_test:
    needs: changes
    if: needs.changes.outputs.js_files == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: pnpm install --workspaces --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build

  ruby_sdk_test:
    needs: changes
    if: needs.changes.outputs.ruby_files == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: 'sdks/ruby'

      - name: Lint
        run: bundle exec rubocop
        working-directory: 'sdks/ruby'

      - name: Run tests
        run: bundle exec rspec
        working-directory: 'sdks/ruby'

  publish:
    needs: js_build_and_test
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: pnpm install --workspaces --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Publish to NPM
        run: pnpm run publish-packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
