name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  filter_changed_paths:
    runs-on: ubuntu-latest
    outputs:
      ts_sdk_files: ${{ steps.filter.outputs.ts_sdk_files }}
      docs_files: ${{ steps.filter.outputs.docs_files }}
      ruby_files: ${{ steps.filter.outputs.ruby_files }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            ts_sdk_files:
              - 'sdks/typescript/**'
              - 'examples/**'
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'pnpm-workspace.yaml'
              - 'workflows/ci.yml'
              - 'tsconfig.base.json'
              - 'vitest.config.ts'
              - 'vitest.setup.ts'
            docs_files:
              - 'docs/**'
            ruby_files:
              - 'sdks/ruby/**'

  js_build_and_test:
    needs: filter_changed_paths
    if: needs.filter_changed_paths.outputs.ts_sdk_files == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: pnpm install --workspaces --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build

  ruby_sdk_test:
    needs: filter_changed_paths
    if: needs.filter_changed_paths.outputs.ruby_files == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: 'sdks/ruby'

      - name: Lint
        run: bundle exec rubocop
        working-directory: 'sdks/ruby'

      - name: Run tests
        run: bundle exec rspec
        working-directory: 'sdks/ruby'

  publish_npm:
    needs: [js_build_and_test, ruby_sdk_test]
    if: github.event_name == 'release' && github.event.action == 'published' && needs.filter_changed_paths.outputs.ts_sdk_files == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --workspaces --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Publish to NPM
        run: pnpm run publish-packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish_ruby_gem:
    needs: [js_build_and_test, ruby_sdk_test]
    if: github.event_name == 'release' && github.event.action == 'published' && needs.filter_changed_paths.outputs.ruby_files == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: 'sdks/ruby'

      - name: Build gem
        run: gem build mcp_ui_server.gemspec
        working-directory: 'sdks/ruby'

      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem push *.gem
        working-directory: 'sdks/ruby'
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
